#pragma once

#include "Windows.h"
#define ID_BUTTON_HELLO   101
#define ID_BUTTON_EXIT    102
#define ID_EDIT_INPUT     103
#define ID_LABEL_STATUS   104
#define ID_BUTTON_MANDELBROTT_DRAW  105
#define ID_BUTTON_JULIA_DRAW  106
#define ID_BUTTON_RESET  107
#define ID_BUTTON_SAVE_FILE  108

#define WM_UPDATE_COORDS (WM_USER + 100)
#define ID_COORDS_BUTTON 1001
#define ID_COORDS_STATIC 1003

